export function customerHomeHtml(): string {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>TaxAgent · Infraestrutura fiscal</title><style>${styles()}</style></head><body><main class="home"><span class="eyebrow">TAXAGENT</span><h1>Fiscal sem integração infinita.</h1><p class="lead">Conecte sua empresa uma vez. O TaxAgent identifica a rota fiscal, mostra o que falta e prepara sua operação para NFS-e com evidência e segurança.</p><div class="actions"><a class="primary" href="/v1/portal">Configurar minha empresa</a><a href="/docs">Documentação API</a></div><section class="features"><article><b>Roteamento fiscal</b><span>Nacional, provedores municipais nativos e fallback controlado.</span></article><article><b>Onboarding guiado</b><span>IM, A1 e credenciais somente quando a rota realmente exigir.</span></article><article><b>Fail-closed</b><span>Readiness e preflight não liberam emissão automaticamente.</span></article></section></main></body></html>`;
}

export function customerPortalHtml(): string {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="robots" content="noindex,nofollow"/><title>TaxAgent · Configuração fiscal</title><style>${styles()}</style></head><body><main class="wrap"><header><div><span class="eyebrow">TAXAGENT · ONBOARDING</span><h1>Prepare sua empresa para operar fiscalmente</h1><p>O TaxAgent identifica a rota correta e pede somente os dados necessários.</p></div><a href="/v1">← Início</a></header>
<section class="card"><h2>1. Acesso da empresa</h2><p class="hint">A chave fica somente na memória desta aba. Nada é salvo em localStorage ou sessionStorage.</p><div class="grid"><label>Company ID<input id="companyId" placeholder="comp_..." autocomplete="off"/></label><label>API key<input id="apiKey" type="password" placeholder="ta_test_..." autocomplete="off"/></label><label>Ambiente<select id="environment"><option value="test">Teste / homologação</option><option value="production">Produção</option></select></label></div><button onclick="connect()">Carregar situação fiscal</button><div id="session" class="status">Nenhuma empresa carregada.</div></section>
<section class="card"><div class="between"><div><h2>2. Jornada fiscal</h2><p class="hint">Checklist calculado pelo motor fiscal.</p></div><button class="secondary" onclick="refreshStatus()">Atualizar</button></div><div id="headline" class="headline">Aguardando conexão…</div><div id="stages" class="stages"></div><pre id="statusOut" class="out">—</pre></section>
<section class="card"><h2>3. Perfil fiscal</h2><div class="grid"><label>Código IBGE<input id="cityCode" maxlength="7" placeholder="3548500"/></label><label>Inscrição Municipal / CCM<input id="municipalRegistration" placeholder="quando aplicável"/></label><label>Regime tributário<input id="taxRegime" placeholder="regular"/></label></div><button onclick="saveProfile()">Salvar e reavaliar</button></section>
<section class="card"><h2>4. Certificado A1</h2><p class="hint">O arquivo e a senha vão direto ao Certificate Vault. O material secreto nunca é devolvido pela API.</p><div class="grid"><label>Arquivo .pfx/.p12<input id="a1File" type="file" accept=".pfx,.p12,application/x-pkcs12"/></label><label>Senha<input id="a1Password" type="password" autocomplete="new-password"/></label></div><button onclick="uploadA1()">Enviar A1 com segurança</button></section>
<section class="card"><h2>5. Credencial municipal/provedor</h2><p class="hint">Preencha somente quando o checklist solicitar. Os valores são cifrados e nunca retornam.</p><div class="grid"><label>Provedor<input id="provider" placeholder="giss"/></label><label>Login<input id="providerLogin" autocomplete="off"/></label><label>Senha/token<input id="providerPassword" type="password" autocomplete="new-password"/></label></div><button onclick="saveProviderCredentials()">Salvar no cofre</button></section>
<section class="card"><h2>6. Validar preparação</h2><p class="hint">Reavalia a empresa e, somente se todos os requisitos locais estiverem completos, executa o preflight não emissor.</p><button onclick="advance()">Validar e avançar</button><div class="guard">Este portal nunca habilita transmissão fiscal automaticamente.</div></section>
<div id="notice" class="notice"></div></main><script>
'use strict';
const state={companyId:'',apiKey:'',environment:'test'};const $=id=>document.getElementById(id);const val=id=>String($(id).value||'').trim();
function requireSession(){if(!state.companyId||!state.apiKey)throw new Error('Informe Company ID e API key.');}
async function request(path,opts={}){requireSession();const headers={accept:'application/json',authorization:'Bearer '+state.apiKey};let body;if(opts.form){body=opts.form}else if(opts.body!==undefined){headers['content-type']='application/json';body=JSON.stringify(opts.body)}const r=await fetch(path,{method:opts.method||'GET',headers,body,cache:'no-store'});const text=await r.text();let data=text;try{data=text?JSON.parse(text):{}}catch{}if(!r.ok)throw new Error('HTTP '+r.status+' · '+(typeof data==='string'?data:JSON.stringify(data)));return data}
function endpoint(suffix=''){return '/v1/portal/companies/'+encodeURIComponent(state.companyId)+'/fiscal'+suffix+'?environment='+encodeURIComponent(state.environment)}
function setNotice(text,ok=true){$('notice').textContent=text;$('notice').className='notice '+(ok?'ok':'err')}
window.connect=async()=>{state.companyId=val('companyId');state.apiKey=val('apiKey');state.environment=val('environment')||'test';$('session').textContent='Empresa ativa: '+state.companyId+' · '+state.environment;await refreshStatus()};
window.refreshStatus=async()=>{try{const data=await request(endpoint());render(data);setNotice('Situação fiscal atualizada.')}catch(e){setNotice(e.message,false)}};
function render(data){$('headline').textContent=(data.fiscal_status||'ACTION_REQUIRED')+(data.route?.resolved_provider?' · '+data.route.resolved_provider:'');$('stages').innerHTML='';(data.stages||[]).forEach(s=>{const el=document.createElement('div');el.className='stage';const b=document.createElement('b');b.textContent=s.label||s.id;const span=document.createElement('span');span.textContent=s.status||'—';const small=document.createElement('small');small.textContent=s.detail||'';el.append(b,span,small);$('stages').appendChild(el)});$('statusOut').textContent=JSON.stringify({status:data.fiscal_status,route:data.route,blockers:data.blockers,next_action:data.next_action,safeguards:data.safeguards},null,2);if(data.company){$('cityCode').value=data.company.city_code||'';$('taxRegime').value=data.company.tax_regime||''}}
window.saveProfile=async()=>{try{const body={};if(val('cityCode'))body.city_code=val('cityCode');if(val('municipalRegistration'))body.municipal_registration=val('municipalRegistration');if(val('taxRegime'))body.tax_regime=val('taxRegime');const data=await request(endpoint('/profile'),{method:'POST',body});render(data);setNotice('Perfil atualizado e reavaliado.')}catch(e){setNotice(e.message,false)}};
window.uploadA1=async()=>{try{requireSession();const file=$('a1File').files[0],password=val('a1Password');if(!file||!password)throw new Error('Selecione o A1 e informe a senha.');const form=new FormData();form.append('file',file);form.append('password',password);await request('/v1/companies/'+encodeURIComponent(state.companyId)+'/certificates/upload',{method:'POST',form});$('a1Password').value='';$('a1File').value='';setNotice('A1 validado e armazenado no Certificate Vault.');await advance()}catch(e){$('a1Password').value='';setNotice(e.message,false)}};
window.saveProviderCredentials=async()=>{try{const provider=val('provider'),login=val('providerLogin'),password=val('providerPassword');if(!provider||(!login&&!password))throw new Error('Informe provedor e credencial.');await request('/v1/companies/'+encodeURIComponent(state.companyId)+'/provider-credentials',{method:'POST',body:{provider,environment:state.environment,credentials:{...(login?{login}:{}),...(password?{password}:{})},note:'Customer Fiscal Portal'}});$('providerPassword').value='';$('providerLogin').value='';setNotice('Credencial cifrada no cofre do provedor.');await advance()}catch(e){$('providerPassword').value='';setNotice(e.message,false)}};
window.advance=async()=>{try{const data=await request(endpoint('/advance'),{method:'POST'});render(data);setNotice(data.fiscal_status==='HOMOLOGATION_READY'?'Fiscal preparado para teste autorizado.':'Validação concluída; veja a próxima ação.')}catch(e){setNotice(e.message,false)}};
</script></body></html>`;
}

function styles(): string { return `:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#171717;background:#f4f5f2}*{box-sizing:border-box}body{margin:0}.home,.wrap{max-width:1040px;margin:0 auto;padding:64px 20px 90px}.home{padding-top:110px}.eyebrow{font-size:12px;font-weight:800;letter-spacing:.14em;color:#41644a}.home h1{font-size:clamp(44px,7vw,82px);line-height:.95;max-width:850px;margin:16px 0}.lead{font-size:21px;line-height:1.55;max-width:720px;color:#555}.actions{display:flex;gap:18px;align-items:center;margin:34px 0}.actions a,.primary{color:#171717;text-decoration:none}.primary,button{display:inline-block;border:0;border-radius:10px;background:#171717;color:white!important;padding:12px 18px;font:inherit;font-weight:750;cursor:pointer}.secondary{background:#e7e9e3;color:#171717!important}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:65px}.features article,.card{background:white;border:1px solid #dedfd9;border-radius:18px;padding:22px}.features article{display:grid;gap:9px}.features span,.hint,header p{color:#666}header{display:flex;justify-content:space-between;gap:20px;align-items:start;margin-bottom:28px}header h1{margin:8px 0;font-size:36px}header a{color:#333}.card{margin:14px 0}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:16px 0}label{font-size:12px;font-weight:750;color:#555}input,select{width:100%;margin-top:5px;border:1px solid #cccec7;border-radius:9px;padding:11px;background:white;font:inherit}.between{display:flex;justify-content:space-between;gap:16px;align-items:start}.status,.guard{margin-top:12px;padding:10px 12px;border-radius:10px;background:#f0f1ed;color:#555}.headline{font-size:22px;font-weight:800;margin:12px 0}.stages{display:grid;gap:8px}.stage{display:grid;grid-template-columns:1fr auto;gap:4px 12px;padding:12px;border:1px solid #e1e2dd;border-radius:10px}.stage small{grid-column:1/-1;color:#6a6a6a}.stage span{font-size:12px;font-weight:800}.out{background:#151515;color:#d9f8d5;border-radius:12px;padding:14px;max-height:270px;overflow:auto;font-size:12px}.notice{position:sticky;bottom:18px;margin-top:18px;padding:12px 16px;border-radius:12px;min-height:20px}.notice.ok{background:#dff4e3}.notice.err{background:#ffe1e1;color:#8b1515}@media(max-width:760px){.grid,.features{grid-template-columns:1fr}header{display:block}.between{align-items:center}.home{padding-top:70px}}`; }
