import { Body, Controller, Get, Param, Post, Query, UploadedFile, UseGuards, UseInterceptors } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { ApiBearerAuth, ApiBody, ApiConsumes, ApiTags } from '@nestjs/swagger';
import { ApiKeyGuard } from '../auth/api-key.guard';
import { TaxAgentAuthContext } from '../auth/auth.types';
import { CurrentTaxAgentAuth } from '../auth/current-auth.decorator';
import { RequireScope } from '../auth/require-scope.decorator';
import { DocumentIntakeFileService, IntakeUploadedFile } from './document-intake-file.service';
import { DocumentIntakeService } from './document-intake.service';
import { DocumentIntakeApprovalRequest, DocumentIntakeRequest } from './document-intake.types';
import { EconomicOperationInput, EconomicOperationService, PaymentAllocationInput } from './economic-operation.service';
import { PaymentInput, PaymentMatchingService } from './payment-matching.service';
import { ReconciliationCasesService, ReconciliationCaseStatus } from './reconciliation-cases.service';

@ApiTags('document-intake') @ApiBearerAuth() @UseGuards(ApiKeyGuard) @Controller('documents')
export class DocumentIntakeController {
  constructor(private readonly intake: DocumentIntakeService, private readonly files: DocumentIntakeFileService, private readonly payments: PaymentMatchingService, private readonly reconciliationCases: ReconciliationCasesService, private readonly operations: EconomicOperationService) {}
  @Post('extract') @RequireScope('documents:write') extract(@Body() body: DocumentIntakeRequest, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.intake.extract(body, auth.companyId, auth.environment); }
  @Post('intake/upload') @RequireScope('documents:write') @UseInterceptors(FileInterceptor('file', { limits: { fileSize: 10 * 1024 * 1024, files: 1 } })) @ApiConsumes('multipart/form-data') @ApiBody({ schema: { type: 'object', required: ['file'], properties: { file: { type: 'string', format: 'binary', description: 'PDF, PNG, JPEG, XML or TXT. Raw bytes are encrypted at rest.' }, document_type: { type: 'string', description: 'auto, nfse, invoice, receipt, bank_statement or contract', default: 'auto' } } } }) upload(@UploadedFile() file: IntakeUploadedFile | undefined, @Body('document_type') documentType: string | undefined, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.files.upload(file, auth.companyId, auth.environment, documentType ?? 'auto'); }
  @Get('intake/files/:fileId') @RequireScope('documents:read') getFile(@Param('fileId') fileId: string, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.files.get(fileId, auth.companyId, auth.environment); }
  @Post('intake/files/:fileId/ocr') @RequireScope('documents:write') startOcr(@Param('fileId') fileId: string, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.files.startOcr(fileId, auth.companyId, auth.environment); }
  @Post('intake/files/:fileId/ocr/poll') @RequireScope('documents:write') pollOcr(@Param('fileId') fileId: string, @Body() body: { document_type?: string }, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.files.pollOcr(fileId, auth.companyId, auth.environment, body?.document_type ?? 'auto'); }
  @Post('intake/files/:fileId/extracted-text') @RequireScope('documents:write') submitExtractedText(@Param('fileId') fileId: string, @Body() body: { text?: string; document_type?: string }, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.files.submitExtractedText(fileId, body?.text ?? '', auth.companyId, auth.environment, body?.document_type ?? 'auto'); }
  @Post('payments') @RequireScope('documents:write') registerPayment(@Body() body: PaymentInput, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.payments.registerPayment(auth.companyId, auth.environment, body); }
  @Post('operations') @RequireScope('documents:write') createOperation(@Body() body: EconomicOperationInput, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.operations.create(auth.companyId, auth.environment, body); }
  @Get('operations') @RequireScope('documents:read') listOperations(@Query('status') status: string | undefined, @Query('limit') limit: string | undefined, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.operations.list(auth.companyId, auth.environment, status, Number(limit ?? 100)); }
  @Get('operations/:operationId') @RequireScope('documents:read') getOperation(@Param('operationId') operationId: string, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.operations.get(operationId, auth.companyId, auth.environment); }
  @Post('operations/:operationId/intakes/:intakeId') @RequireScope('documents:write') linkOperationIntake(@Param('operationId') operationId: string, @Param('intakeId') intakeId: string, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.operations.linkIntake(operationId, intakeId, auth.companyId, auth.environment); }
  @Post('operations/:operationId/payments/:paymentId') @RequireScope('documents:write') linkOperationPayment(@Param('operationId') operationId: string, @Param('paymentId') paymentId: string, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.operations.linkPayment(operationId, paymentId, auth.companyId, auth.environment); }
  @Post('operations/:operationId/payments/:paymentId/allocate') @RequireScope('documents:write') allocateOperationPayment(@Param('operationId') operationId: string, @Param('paymentId') paymentId: string, @Body() body: PaymentAllocationInput, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.operations.allocatePayment(operationId, paymentId, auth.companyId, auth.environment, body); }
  @Get('reconciliation') @RequireScope('documents:read') reconciliation(@Query('days') days: string | undefined, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.payments.reconciliationReport(auth.companyId, auth.environment, Number(days ?? 45)); }
  @Post('reconciliation/sync') @RequireScope('documents:write') async syncReconciliation(@Query('days') days: string | undefined, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { const report = await this.payments.reconciliationReport(auth.companyId, auth.environment, Number(days ?? 45)); const sync = await this.reconciliationCases.sync(auth.companyId, auth.environment, report.issues); return { report, sync }; }
  @Get('reconciliation/cases') @RequireScope('documents:read') listReconciliationCases(@Query('status') status: string | undefined, @Query('severity') severity: string | undefined, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.reconciliationCases.list(auth.companyId, auth.environment, status, severity); }
  @Get('reconciliation/cases/:caseId') @RequireScope('documents:read') getReconciliationCase(@Param('caseId') caseId: string, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.reconciliationCases.get(caseId, auth.companyId, auth.environment); }
  @Post('reconciliation/cases/:caseId/status') @RequireScope('documents:write') transitionReconciliationCase(@Param('caseId') caseId: string, @Body() body: { status?: ReconciliationCaseStatus; resolution_code?: string; note?: string }, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.reconciliationCases.transition(caseId, auth.companyId, auth.environment, body?.status as ReconciliationCaseStatus, body?.resolution_code, body?.note); }
  @Get('intake/:intakeId') @RequireScope('documents:read') get(@Param('intakeId') intakeId: string, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.intake.get(intakeId, auth.companyId, auth.environment); }
  @Post('intake/:intakeId/approve') @RequireScope('documents:write') approve(@Param('intakeId') intakeId: string, @Body() body: DocumentIntakeApprovalRequest, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.intake.approveAndPost(intakeId, auth.companyId, auth.environment, body); }
  @Post('intake/:intakeId/payment-matches') @RequireScope('documents:write') suggestPaymentMatches(@Param('intakeId') intakeId: string, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { return this.payments.suggest(intakeId, auth.companyId, auth.environment); }
  @Post('intake/:intakeId/payment-matches/:paymentId/confirm') @RequireScope('documents:write') async confirmPaymentMatch(@Param('intakeId') intakeId: string, @Param('paymentId') paymentId: string, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { const reconciliation = await this.payments.confirm(intakeId, paymentId, auth.companyId, auth.environment); const economicOperation = await this.operations.bindConfirmedMatch(intakeId, paymentId, auth.companyId, auth.environment); return { ...reconciliation, economic_operation: economicOperation }; }
  @Get('intake/:intakeId/payment-status') @RequireScope('documents:read') async paymentStatus(@Param('intakeId') intakeId: string, @CurrentTaxAgentAuth() auth: TaxAgentAuthContext) { const payment = await this.payments.paymentStatus(intakeId, auth.companyId, auth.environment); const economicOperation = await this.operations.findByIntake(intakeId, auth.companyId, auth.environment); return { ...payment, economic_operation: economicOperation ?? undefined }; }
}
